import mongoose from 'mongoose';

const payrollSchema = new mongoose.Schema(
  {
    employee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Employee is required'],
    },
    weekStartDate: {
      type: Date,
      required: [true, 'Week start date is required'],
    },
    weekEndDate: {
      type: Date,
      required: [true, 'Week end date is required'],
    },
    // Summary of hours
    regularHours: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    overtimeHours: {
      type: Number,
      default: 0,
      min: 0,
    },
    totalHours: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    // Wage details at time of payroll generation
    hourlyRate: {
      type: Number,
      required: true,
      min: 0,
    },
    overtimeRate: {
      type: Number,
      default: 1.5, // 1.5x regular rate
    },
    // Calculated amounts
    regularPay: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    overtimePay: {
      type: Number,
      default: 0,
      min: 0,
    },
    // Deductions and bonuses
    deductions: {
      type: Number,
      default: 0,
      min: 0,
    },
    bonuses: {
      type: Number,
      default: 0,
      min: 0,
    },
    // Final amounts
    grossPay: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    netPay: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
    },
    // Payment status
    status: {
      type: String,
      enum: ['pending', 'approved', 'paid', 'disputed'],
      default: 'pending',
    },
    paidAt: {
      type: Date,
      default: null,
    },
    paidBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    paymentMethod: {
      type: String,
      enum: ['cash', 'bank_transfer', 'cheque', 'other'],
      default: 'cash',
    },
    paymentReference: {
      type: String,
      trim: true,
    },
    // Notes
    notes: {
      type: String,
      trim: true,
      maxlength: [500, 'Notes cannot exceed 500 characters'],
    },
    // Associated shifts for reference
    shifts: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Shift',
    }],
    // Generated by
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Unique index for employee per week
payrollSchema.index({ employee: 1, weekStartDate: 1 }, { unique: true });
payrollSchema.index({ status: 1 });
payrollSchema.index({ weekStartDate: 1, weekEndDate: 1 });

// Pre-save middleware to calculate pay
payrollSchema.pre('save', function (next) {
  // Calculate regular pay
  this.regularPay = parseFloat((this.regularHours * this.hourlyRate).toFixed(2));
  
  // Calculate overtime pay (1.5x rate by default)
  this.overtimePay = parseFloat((this.overtimeHours * this.hourlyRate * this.overtimeRate).toFixed(2));
  
  // Calculate total hours
  this.totalHours = parseFloat((this.regularHours + this.overtimeHours).toFixed(2));
  
  // Calculate gross pay
  this.grossPay = parseFloat((this.regularPay + this.overtimePay + this.bonuses).toFixed(2));
  
  // Calculate net pay
  this.netPay = parseFloat((this.grossPay - this.deductions).toFixed(2));
  
  next();
});

// Static method to get week boundaries
payrollSchema.statics.getWeekBoundaries = function (date) {
  const inputDate = new Date(date);
  const dayOfWeek = inputDate.getDay();
  
  // Get Monday of the week
  const monday = new Date(inputDate);
  monday.setDate(inputDate.getDate() - (dayOfWeek === 0 ? 6 : dayOfWeek - 1));
  monday.setHours(0, 0, 0, 0);
  
  // Get Sunday of the week
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  sunday.setHours(23, 59, 59, 999);
  
  return { weekStart: monday, weekEnd: sunday };
};

/**
 * Static method to auto-calculate/update payroll when a shift is completed
 * This creates or updates the weekly payroll record automatically
 */
payrollSchema.statics.calculateForShift = async function (shift, User) {
  const Shift = (await import('./Shift.js')).default;
  
  // Get week boundaries for the shift date
  const { weekStart, weekEnd } = this.getWeekBoundaries(shift.date);
  
  // Get all completed shifts for this employee this week
  const completedShifts = await Shift.find({
    employee: shift.employee,
    date: { $gte: weekStart, $lte: weekEnd },
    status: 'completed',
  });

  if (completedShifts.length === 0) {
    return null;
  }

  // Get employee details for hourly rate
  const employee = await User.findById(shift.employee);
  if (!employee) {
    throw new Error('Employee not found');
  }

  // Ensure we have a valid hourly rate
  const hourlyRate = employee.hourlyWage || employee.hourlyRate || 10;

  // Calculate total hours
  const regularHours = completedShifts.reduce((sum, s) => sum + (s.hoursWorked || 0), 0);
  const overtimeHours = completedShifts.reduce((sum, s) => sum + (s.overtimeHours || 0), 0);

  // Find existing payroll or create new one
  let payroll = await this.findOne({
    employee: shift.employee,
    weekStartDate: weekStart,
  });

  const payrollData = {
    employee: shift.employee,
    weekStartDate: weekStart,
    weekEndDate: weekEnd,
    regularHours: parseFloat(regularHours.toFixed(2)),
    overtimeHours: parseFloat(overtimeHours.toFixed(2)),
    totalHours: parseFloat((regularHours + overtimeHours).toFixed(2)),
    hourlyRate: hourlyRate,
    shifts: completedShifts.map((s) => s._id),
    generatedBy: shift.employee, // Auto-generated
  };

  if (payroll) {
    // Check if new shifts were added after payment
    const currentShiftCount = payroll.shifts?.length || 0;
    const newShiftCount = completedShifts.length;
    
    if (payroll.status === 'paid' && newShiftCount > currentShiftCount) {
      // New shifts completed after payment - update and change status to pending
      // This means additional payment is owed
      Object.assign(payroll, payrollData);
      payroll.status = 'pending';
      payroll.paidAt = null;
      payroll.paymentReference = null;
      await payroll.save();
      console.log(`⚠️ Payroll reopened: New shifts added after payment. Status changed to pending.`);
    } else if (payroll.status !== 'paid') {
      // Normal update for unpaid payroll
      Object.assign(payroll, payrollData);
      await payroll.save();
    }
    // If paid and no new shifts, don't update
  } else {
    // Create new payroll record
    payroll = await this.create(payrollData);
  }

  return payroll;
};

const Payroll = mongoose.model('Payroll', payrollSchema);

export default Payroll;
